// Mocks generated by Mockito 5.4.6 from annotations
// in bnpl_app/test/presentation/splash/splash_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bnpl_app/domain/usecases/get_all_installments.dart' as _i3;
import 'package:bnpl_app/domain/usecases/get_all_products.dart' as _i2;
import 'package:bnpl_app/presentation/products/bloc/products_bloc.dart' as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAllProducts_0 extends _i1.SmartFake
    implements _i2.GetAllProducts {
  _FakeGetAllProducts_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllInstallments_1 extends _i1.SmartFake
    implements _i3.GetAllInstallments {
  _FakeGetAllInstallments_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsState_2 extends _i1.SmartFake implements _i4.ProductsState {
  _FakeProductsState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsBloc extends _i1.Mock implements _i4.ProductsBloc {
  MockProductsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAllProducts get getAllProducts =>
      (super.noSuchMethod(
            Invocation.getter(#getAllProducts),
            returnValue: _FakeGetAllProducts_0(
              this,
              Invocation.getter(#getAllProducts),
            ),
          )
          as _i2.GetAllProducts);

  @override
  _i3.GetAllInstallments get getAllInstallments =>
      (super.noSuchMethod(
            Invocation.getter(#getAllInstallments),
            returnValue: _FakeGetAllInstallments_1(
              this,
              Invocation.getter(#getAllInstallments),
            ),
          )
          as _i3.GetAllInstallments);

  @override
  _i4.ProductsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProductsState_2(this, Invocation.getter(#state)),
          )
          as _i4.ProductsState);

  @override
  _i5.Stream<_i4.ProductsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i4.ProductsState>.empty(),
          )
          as _i5.Stream<_i4.ProductsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i4.ProductsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.ProductsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.ProductsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.ProductsEvent>(
    _i6.EventHandler<E, _i4.ProductsState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i6.Transition<_i4.ProductsEvent, _i4.ProductsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i4.ProductsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onChange(_i6.Change<_i4.ProductsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
