// Mocks generated by Mockito 5.4.6 from annotations
// in bnpl_app/test/presentation/products/bloc/products_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bnpl_app/core/network/app_exception.dart' as _i6;
import 'package:bnpl_app/core/usecases/usecase.dart' as _i8;
import 'package:bnpl_app/data/models/available_plan_model.dart' as _i10;
import 'package:bnpl_app/domain/entities/product.dart' as _i7;
import 'package:bnpl_app/domain/repositiories/bnpl_repository.dart' as _i2;
import 'package:bnpl_app/domain/usecases/get_all_installments.dart' as _i9;
import 'package:bnpl_app/domain/usecases/get_all_products.dart' as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBnplRepository_0 extends _i1.SmartFake
    implements _i2.BnplRepository {
  _FakeBnplRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProducts extends _i1.Mock implements _i4.GetAllProducts {
  MockGetAllProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BnplRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBnplRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BnplRepository);

  @override
  _i5.Future<_i3.Either<_i6.AppException, List<_i7.Product>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.AppException, List<_i7.Product>>
                >.value(
                  _FakeEither_1<_i6.AppException, List<_i7.Product>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.AppException, List<_i7.Product>>>);
}

/// A class which mocks [GetAllInstallments].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllInstallments extends _i1.Mock
    implements _i9.GetAllInstallments {
  MockGetAllInstallments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BnplRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBnplRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BnplRepository);

  @override
  _i5.Future<_i3.Either<_i6.AppException, List<_i10.AvailablePlanModel>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.AppException, List<_i10.AvailablePlanModel>>
                >.value(
                  _FakeEither_1<
                    _i6.AppException,
                    List<_i10.AvailablePlanModel>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i5.Future<
            _i3.Either<_i6.AppException, List<_i10.AvailablePlanModel>>
          >);
}
