// Mocks generated by Mockito 5.4.6 from annotations
// in bnpl_app/test/domain/usecases/get_all_products_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bnpl_app/core/network/app_exception.dart' as _i5;
import 'package:bnpl_app/data/models/available_plan_model.dart' as _i7;
import 'package:bnpl_app/domain/entities/product.dart' as _i6;
import 'package:bnpl_app/domain/repositiories/bnpl_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BnplRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBnplRepository extends _i1.Mock implements _i3.BnplRepository {
  MockBnplRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppException, List<_i6.Product>>>
  getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, List<_i6.Product>>
                >.value(
                  _FakeEither_0<_i5.AppException, List<_i6.Product>>(
                    this,
                    Invocation.method(#getAllProducts, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppException, _i6.Product>> getProductDetails(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.AppException, _i6.Product>>.value(
                  _FakeEither_0<_i5.AppException, _i6.Product>(
                    this,
                    Invocation.method(#getProductDetails, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, _i6.Product>>);

  @override
  _i4.Future<_i2.Either<_i5.AppException, List<_i7.AvailablePlanModel>>>
  getAllInstallments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllInstallments, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.AppException, List<_i7.AvailablePlanModel>>
                >.value(
                  _FakeEither_0<_i5.AppException, List<_i7.AvailablePlanModel>>(
                    this,
                    Invocation.method(#getAllInstallments, []),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.AppException, List<_i7.AvailablePlanModel>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.AppException, int>> createOrder(
    int? productId,
    int? planId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [productId, planId]),
            returnValue: _i4.Future<_i2.Either<_i5.AppException, int>>.value(
              _FakeEither_0<_i5.AppException, int>(
                this,
                Invocation.method(#createOrder, [productId, planId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, int>>);

  @override
  _i4.Future<_i2.Either<_i5.AppException, bool>> checkCard(
    Map<String, dynamic>? cardDetails,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkCard, [cardDetails]),
            returnValue: _i4.Future<_i2.Either<_i5.AppException, bool>>.value(
              _FakeEither_0<_i5.AppException, bool>(
                this,
                Invocation.method(#checkCard, [cardDetails]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AppException, bool>>);
}
